# Automated Essay Checking

** Each cell contains a description in the beginnning followed the by code that executes the task in the description of the cell.**

**Begin: Importing data structures to hold the data**  

Importing NumPy and Pandas, these data structures will hold the training and testing data.
The total number of columns and length of the data-set is been printed at the end of the code execution.

In [3]:
import sys
sys.path.append('./utils')

In [4]:
#Imports
from requirements import *
import helperfunctions as helper

In [5]:
# Import libraries and data.

essay_data = pd.read_csv("domain123.csv")
essay_data = essay_data.dropna(axis=1)
essay_data = essay_data.drop('rater1_domain1',1)
essay_data = essay_data.drop('rater2_domain1',1)
essay_data = essay_data.drop('essay_id',1)

print(essay_data.columns)
print("Length of the data=",len(essay_data))


Index([u'essay_set', u'essay', u'domain1_score'], dtype='object')
('Length of the data=', 5309)


In [6]:
#Preprocessing, generating feature columns.
feature_data = helper.preprocess_data2feature(essay_data,'domain1_score')
feature_data.head()

essay word_count  \
0  Dear local newspaper, I think effects computer...        NaN   
1  Dear @CAPS1 @CAPS2, I believe that using compu...        NaN   
2  Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...        NaN   
3  Dear Local Newspaper, @CAPS1 I have found that...        NaN   
4  Dear @LOCATION1, I know having computers has a...        NaN   

  long_word_count avg_word_length_per_essay wrong_words no_of_domain_words  \
0             NaN                       NaN         NaN                NaN   
1             NaN                       NaN         NaN                NaN   
2             NaN                       NaN         NaN                NaN   
3             NaN                       NaN         NaN                NaN   
4             NaN                       NaN         NaN                NaN   

  word_to_sent_ratio num_of_characters sentence_count noun_count verb_count  \
0                NaN               NaN            NaN        NaN        NaN   
1                NaN               NaN            NaN        NaN        NaN   
2                NaN               NaN            NaN        NaN        NaN   
3                NaN               NaN            NaN        NaN        NaN   
4                NaN               NaN            NaN        NaN        NaN   

  comma_count punctuation_count adjective_count adverb_count  \
0         NaN               NaN             NaN          NaN   
1         NaN               NaN             NaN          NaN   
2         NaN               NaN             NaN          NaN   
3         NaN               NaN             NaN          NaN   
4         NaN               NaN             NaN          NaN   

  quotation_mark_count spelling_mistakes  target  
0                  NaN               NaN       8  
1                  NaN               NaN       9  
2                  NaN               NaN       7  
3                  NaN               NaN      10  
4                  NaN               NaN       8

In [7]:
feature_cols = list(feature_data.columns[:-1])
X_all = feature_data[feature_cols]
y_all = feature_data['target'] #domain1_score is equal to sum of rater_domain1 and rater_domain2, so that columns are not needed


In [11]:
X_all[80:103]

essay word_count  \
80   Dear Local Newspaper, I think that using compu...        251   
81   Do you remember the last time you locked somet...        199   
82   Dear Newspaper Computers have been a great lea...        135   
83   I think computers help people out because you ...        130   
84   Dear local newspaper, Computers are they a goo...        383   
85   Dear Newspaper, @CAPS1 computers become more a...        301   
86   Computers. One of the much enjoyed pieces of t...        308   
87   Dear Newspaper, "@CAPS1 no!' I forgot the deff...        284   
88   Computers do benefit are society. They have ch...        156   
89   Dear @CAPS1 and @CAPS2 of the @LOCATION1 @CAPS...        153   
90   Dear Newspaper, I think computers are great. T...        155   
91   Dear local Newspaper; @CAPS1 you know that com...        463   
92   Readers of "@LOCATION2 @CAPS1" should be well ...        371   
93   Dear Newspaper people, I'm here to tell you th...        221   
94   Although some people believe that computers tu...        322   
95   The use of computers is definetly correct. It ...        158   
96   Dear Local @CAPS1, I think computers benefit s...        201   
97   Dear @ORGANIZATION1, In this new digital age, ...        293   
98   Dear @CAPS1: Have you been sent a photo of a @...        236   
99   Dear local newspaper, @CAPS1 you know how long...        158   
100  Dear Local Newspaper, Have you ever gone somew...        NaN   
101  Dear Local Newspaper, Experts should not be co...        NaN   
102  Dear Local Newspaper, Have you ever been runni...        NaN   

    long_word_count avg_word_length_per_essay wrong_words no_of_domain_words  \
80               55                       4.6          55                196   
81               73                      5.38          45                154   
82               34                      4.86          31                104   
83               16                      4.28          34                 96   
84               99                      4.88         100                283   
85              101                      5.69          44                257   
86               56                      4.71          86                222   
87               54                      4.55          61                223   
88               44                      5.02          36                120   
89               38                      4.69          36                117   
90               39                       5.1          22                133   
91               92                      4.45         106                357   
92              140                      5.68          84                287   
93               41                      4.62          53                168   
94               64                      4.39          69                253   
95               48                      5.09          35                123   
96               56                       5.1          45                156   
97               76                      5.03          66                227   
98               45                      4.49          67                169   
99               31                      4.29          35                123   
100             NaN                       NaN         NaN                NaN   
101             NaN                       NaN         NaN                NaN   
102             NaN                       NaN         NaN                NaN   

    word_to_sent_ratio num_of_characters sentence_count noun_count verb_count  \
80               15.69              1894             16         79         57   
81                9.05              1635             22         71         36   
82                  15              1084              9         44         29   
83               11.82               953             11         37         30   
84               12.35              2996             31        110

In [23]:
#Generate the feature set.
#print len(X_all)
#helper.GenerateFeatures(X_all[:50])
#helper.GenerateFeatures(X_all[50:100])
#helper.GenerateFeatures(X_all[100:900])
#helper.GenerateFeatures(X_all[900:1700])
#helper.GenerateFeatures(X_all[1700:2500])
#helper.GenerateFeatures(X_all[2500:3300])
#helper.GenerateFeatures(X_all[3300:4100])
#helper.GenerateFeatures(X_all[4100:4900])
#helper.GenerateFeatures(X_all[4900:])
print "Done"

made features for rows with index upto  4600
made features for rows with index upto  4610
made features for rows with index upto  4620
made features for rows with index upto  4630
made features for rows with index upto  4640
made features for rows with index upto  4650
made features for rows with index upto  4660
made features for rows with index upto  4670
made features for rows with index upto  4680
made features for rows with index upto  4690
made features for rows with index upto  4700
made features for rows with index upto  4710
made features for rows with index upto  4720
made features for rows with index upto  4730
made features for rows with index upto  4740
made features for rows with index upto  4750
made features for rows with index upto  4760
made features for rows with index upto  4770
made features for rows with index upto  4780
made features for rows with index upto  4790
made features for rows with index upto  4800
made features for rows with index upto  4810
made featu

In [30]:
# Save the features generated to a .csv file in case of failure or recovery purpose.
X_all_feature_vec = np.array(X_all.drop('essay',axis=1))
X_all.to_csv('model_and_visualization/features_set_1.csv')
y_all.to_csv('model_and_visualization/target_set_1.csv')
np.save('model_and_visualization/custom-feature-vectors.npy',X_all_feature_vec)

X_all_feature_vec

array([[236, 54, 4.83, ..., 10, 4, 0],
       [281, 76, 4.93, ..., 17, 3, 1],
       [188, 51, 5.01, ..., 10, 4, 6],
       ..., 
       [79, 23, 4.85, ..., 6, 0, 1],
       [112, 24, 4.77, ..., 10, 0, 0],
       [86, 23, 4.92, ..., 4, 0, 2]], dtype=object)

In [36]:
feature_columns = ["word_count","long_word_count","avg_word_length_per_essay","wrong_words","no_of_domain_words","word_to_sent_ratio","num_of_characters","sentence_count","noun_count","verb_count","comma_count","punctuation_count","adjective_count","adverb_count","quotation_mark_count","spelling_mistakes"]
feature_dict = {}
    
for f in feature_columns:
    score = Evaluate2(X_all,y_all,[f])
    feature_dict[f] = round(float(score)*100,4)
feature_dict

[ 5.21290552  6.4907013   6.47511842  6.8646903   5.10382539]
[ 5.4140814   5.47704458  4.40667037  7.05112431  3.28907376]
[ 5.90218634  4.4598549   4.02560457  7.0033211   3.59135424]
[ 7.01470583  7.67996405  5.31099576  2.0496079   4.72686659]
[ 6.93439774  3.39753312  5.56327842  2.36919363  5.3918885 ]
[ 6.36661428  6.8934595   6.483691    4.7275403   7.71299649]
[ 3.92464806  3.05260973  3.86651217  2.29684318  5.95940417]
[ 8.29839639  5.82797557  5.23978014  4.41630654  5.5926974 ]
[ 5.10663199  4.92440325  6.13926154  4.62068868  8.02229188]
[ 6.70900618  6.29135237  3.48710538  5.27705027  6.29135237]
[ 4.58484426  4.86057302  4.43887021  4.76325699  4.74703765]
[ 5.43131196  4.23048979  5.69302961  4.8924815   4.47681229]
[ 4.81888671  4.91284775  4.17681959  5.35133261  4.49002306]
[ 4.83742239  4.10162572  4.75914615  4.72783565  4.14859146]
[ 4.8924151   4.49764529  4.16603864  4.13445706  5.33455729]
[ 3.97742945  4.48823374  6.75847505  3.23960102  7.38279141]
[ 6.3989

{'adjective_count': 45.6087,
 'adverb_count': 45.0675,
 'avg_word_length_per_essay': 6.2907,
 'comma_count': 29.3803,
 'long_word_count': 52.7213,
 'no_of_domain_words': 54.1305,
 'noun_count': 58.1757,
 'num_of_characters': 52.476,
 'punctuation_count': 36.8908,
 'quotation_mark_count': 16.7619,
 'sentence_count': 57.31,
 'spelling_mistakes': 27.6624,
 'verb_count': 49.1978,
 'word_count': 52.9459,
 'word_to_sent_ratio': 3.6408,
 'wrong_words': 42.8749}

# Visualizing single-feature kappa scores


In [ ]:
#Single feature Kappa
import operator
sorted_feature_list = sorted(feature_dict.items(), key=operator.itemgetter(1),reverse=True)
#sorted_feature_list

print "\t\tIndex\t Feature"
for x in range(len(sorted_feature_list)):
    print "\t\t|",x,"|\t|",sorted_feature_list[x][0],"|"
    print "\t\t--------------------------------"

objects = [x[1] for x in sorted_feature_list]
y_pos = np.arange(len(objects))
plt.bar(y_pos, objects, align='center', alpha=0.5)
#plt.xticks(y_pos, objects)
plt.ylabel('Kappa score')
plt.title('Single feature Kappa')
plt.show()

In [ ]:
#Forward feature selection.
sorted_f = [i[0] for i in sorted_feature_list]
objects = []
results = []
for i in range(1,len(sorted_f)+1):
    forward_feature_list = sorted_f[:i]
    round(float(score)*100,4)
    result = round(float(Evaluate(forward_feature_list))*100,4)
    results.append(result)
    objects.append(forward_feature_list)
     
print "Index   Forward Feature list"
#for x in range(len(objects)):
    #print x,"  ",objects[x]
    #print "--------------------------------------------------"
        
y_pos = np.arange(len(objects))
plt.bar(y_pos,results)
plt.show()

**Manually selecting best performing feature-set from the results obtained through forward feature selection**

Selected the features whose inclusion resulted in an increase in the Kappa-Score, according to the values and the graphs, the indexes of selected feature are {0,1,2,3,5,8,10,11,13,14,15}

In [ ]:
selected_indexes  = [0,1,2,3,5,8,10,11,13,14,15] #Do not delete
selected_features = [sorted_f[i] for i in selected_indexes]

print Evaluate(selected_features)

selected_features


# Data exploration

The plots below allows us to view the underlying trends within the data. The plots visualize how the 11 selected features through forward feature selection impact the grade of an essay.

In [ ]:
def plots(x,y,xlabel,title,ax,color='b'):
    ax.scatter(x,y,color = color)
    ax.set_ylabel('Grade')
    ax.set_xlabel(xlabel)
    ax.set_title(title)
    
    

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

fig, ((ax1, ax2), (ax3, ax4), (ax5, ax6),(ax7, ax8),(ax9, ax10)) = plt.subplots(5, 2, figsize=(15, 25))
axs = [ax1,ax2,ax3,ax4,ax5,ax6,ax7,ax8,ax9,ax10]
for i in range(len(selected_features)-1):
    plots(X_all[selected_features[i]],y_all,selected_features[i],selected_features[i] +" v/s Grade",axs[i])
    
fig.savefig('model_and_visualization/Essay1Features.png', bbox_inches = "tight")
  
fig, ax = plt.subplots()
plots(X_all['word_to_sent_ratio'],y_all,'word_to_sent_ratio','word_to_sent_ratio v/s Grade',ax)

# Observation

As expected, we were able to see general trends between the sentence structure of an essay and the grade it received. Noteably, we see that it is not uncommon to see essays with a large number of spelling mistakes receive a high grade. One could make the assumption that techonology's (Word's Spell Check) influence on writing has made it less imperitive for students to spell correctly. It seems as though the message carries more weight than specific errors in the essay.

In [ ]:
tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')
cv = KFold(len(X_all), n_folds=5,shuffle=True)
results = []

for traincv, testcv in cv:
        X_test, X_train, y_test, y_train = X_all.iloc[testcv], X_all.iloc[traincv], y_all.iloc[testcv], y_all.iloc[traincv]
                
        train_essays = X_train['essay']
        test_essays = X_test['essay']
        #print essays
        sentences = []

        print ("Performing sentence and word tokenizing which will be used for word2vec")

        for essay in train_essays:
            sentences += essay_to_sentences(unicode(essay,"utf-8",errors='ignore'), remove_stopwords = True)

        for essay in test_essays:
            sentences += essay_to_sentences(unicode(essay,"utf-8",errors='ignore'), remove_stopwords = True)

        #print(len(sentences))
        #print("Done")
        
        logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

        num_features = 300 
        min_word_count = 40
        num_workers = 4
        context = 10
        downsampling = 1e-3

        #print ("Training w2v model...")
        model = word2vec.Word2Vec(sentences, workers=num_workers, size=num_features, min_count = min_word_count, window = context, sample = downsampling)

        model.init_sims(replace=True)

        model_name = "model_and_visualization/300features_40minwords_10context"
        model.save(model_name)

        #print ("Done")
        
        #print ("Creating average feature vecs for Training Essays")
        clean_train_essays = []
      
        for essay_v in train_essays:
            clean_train_essays.append( essay_to_wordlist( essay_v, remove_stopwords=True ))
        trainDataVecs = getAvgFeatureVecs( clean_train_essays, model, num_features )
        
        clean_test_essays = []
        for essay_v in test_essays:
            clean_test_essays.append( essay_to_wordlist( essay_v, remove_stopwords=True ))
        testDataVecs = getAvgFeatureVecs( clean_test_essays, model, num_features )
        
        #print("Done")

        myOwnTrainFeatureVec = np.array(X_train[selected_features])
        myOwnTestFeatureVec = np.array(X_test[selected_features])
        
        trainDataVecs2 = np.concatenate((trainDataVecs,myOwnTrainFeatureVec),1)
        testDataVecs2 = np.concatenate((testDataVecs,myOwnTestFeatureVec),1)
        
        model = LinearRegression()
        model.fit(trainDataVecs2,y_train)
        start = time()
        y_pred = model.predict(testDataVecs2)
        end = time()

        #print ("Made predictions in {:.4f} seconds.".format(end - start))
        result = kappa(y_test.values,np.around(y_pred,decimals=2),weights='quadratic')
        print "Kappa: ", result
        results.append(result)
        
print np.array(results).mean()